image: sheludchenko/agent-controller:latest
pullPolicy: "ifNotPresent"
imagePullSecrets: []

pollInterval: 10000

agent:
  poolName: Default
  workDirectory: _work
  organizationUrl: https://dev.azure.com/{organization}
  image: docker.io/btungut/azure-devops-agent:2.214.1
  personalAccessToken: 

serviceAccountAnnotations: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
