apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent-controller.fullname" . }}
  labels:
    {{- include "agent-controller.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "agent-controller.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "agent-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
