apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-controller.fullname" . }}-pat
  labels:
  {{- include "agent-controller.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  pat: {{ .Values.agent.personalAccessToken | b64enc }}
