apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-controller.serviceAccountName" . }}
  labels:
    {{- include "agent-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
